### ISSUE TITLE
Adding TELEMETRY for FPV QUADS

### ISSUE THREAD

**Issue by digitalomni** [ilihack/LuaPilot_Taranis_Telemetry#4]
I have a SPF3 Flight controller that puts out the flight modes in the Temp1 or Tmp1.
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwiw0vnnys7OAhUIVyYKHaxRBzoQjRwIBw&url=http%3A%2F%2Fwww.rjxhobby.com%2Frjx-q3083&psig=AFQjCNHHQzjzXy8tjBcJfNnPACL7mQROgA&ust=1471734075485874

The data comes through as a 5 digit number with the last 2 digits indicating flight modes and arm status. I would really like to see if anyone would be interested in adding this additional data so all the FPV pilots could use this script..  I also would like to have an indicator showing if the drone is ARMED. 

For example
10000= ACRO MODE + not ready to arm
10001 = ACRO MODE + Ready to Arm
10005 = ACRO MODE + Armed
10015 = ANGLE MODE + Armed
10025 = HORIZON MODE + Armed

I was trying to figure out the code myself but did not know how to only look at the first two digits starting from the right?

 @thedevleon Any thoughts?

**Comment by ilihack** [comment]
sorry maybe here is the wrong place for help
