### ISSUE TITLE
OpenTX 2.2

### ISSUE THREAD

**Issue by Bingisser** [ilihack/LuaPilot_Taranis_Telemetry#6]
With OpenTX 2.2 the Telemetry Script name must be 6 caracters or less. So change shorten the scriptname.

Something with speed calculation isn't correct. I change it the following way:

629  drawText(getLastPos(), 25, round(data.spd*1.851), MIDSIZE)
630  drawText(getLastPos(), 29, "kmh", SMLSIZE)
to
629  drawText(getLastPos(), 25, round(data.spd*1.851*2), MIDSIZE)
630  drawText(getLastPos(), 29, "km/h", SMLSIZE)

**Comment by Johnex** [comment]
I can confirm that these 2 fixes are needed for the script to work on the just released OpenTX 2.2

**Comment by ilihack** [comment]
tank you Bingisser and Johnex 👍
