### ISSUE TITLE
OpenTX 2.2 / 2.1: Battery percentage callout

### ISSUE THREAD

**Issue by j3ling** [ilihack/LuaPilot_Taranis_Telemetry#8]
For OpenTX 2.2 the SayBattPercent() function needs to be changed, as the unit parameter of the playNumber function has changed (see https://github.com/opentx/lua-reference-guide/blob/master/general/playNumber.md). The original script calls "Miles per Hour" instead of "Percent" as unit.

To fix this 
playNumber(round(lastsaynbattpercent), 8, 0)
needs to be 
playNumber(round(lastsaynbattpercent), 13, 0) 
for openTX 2.2

**Comment by gulp79** [comment]
Thanks! fix added.
